Error:  Define and throw a dedicated exception instead of using generic one.
Explanation: Dedicated exceptions are better compared to generic exceptions because the dedicated exceptions clearly explains about the exception caused in the application.